apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod
  labels:
    app: advanced-multi-container
spec:
  initContainers:
  - name: config-manager
    image: busybox:1.35
    command: ["/bin/sh", "-c"]
    args:
    - |
      cat > /nginx-config/default.conf << 'EOF'
      server {
          listen 80;
          server_name localhost;

          location / {
              root /usr/share/nginx/html;
              index index.html;
          }

          location /metrics {
              proxy_pass http://localhost:9090/metrics;
          }

          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
      }
      EOF

      cat > /fluentbit-config/fluent-bit.conf << 'EOF'
      [SERVICE]
          Flush         1
          Log_Level     info
          Daemon        off

      [INPUT]
          Name              tail
          Path              /var/log/nginx/access.log
          Parser            nginx
          Tag               nginx.access

      [OUTPUT]
          Name              stdout
          Match             *
      EOF

      cat > /prometheus-config/prometheus.yml << 'EOF'
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'nginx'
          static_configs:
            - targets: ['localhost:80']
      EOF

      cat > /usr/share/nginx/html/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>Advanced Pod Demo</title>
      </head>
      <body>
          <h1>Advanced Multi-Container Pod</h1>
          <p>This demonstrates:</p>
          <ul>
              <li>Sidecar pattern with log aggregation</li>
              <li>Ambassador pattern with metrics proxy</li>
              <li>Inter-container communication</li>
              <li>Shared volumes and networking</li>
          </ul>
          <p><a href="/metrics">View Metrics</a></p>
      </body>
      </html>
      EOF
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html
    - name: nginx-config
      mountPath: /nginx-config
    - name: fluentbit-config
      mountPath: /fluentbit-config
    - name: prometheus-config
      mountPath: /prometheus-config

  containers:
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
    - name: shared-logs
      mountPath: /var/log/nginx

  - name: log-aggregator
    image: fluent/fluent-bit:2.0
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
      readOnly: true
    - name: fluentbit-config
      mountPath: /fluent-bit/etc

  - name: metrics-proxy
    image: prom/prometheus:v2.40.0
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-config
      mountPath: /etc/prometheus
    command:
    - /bin/prometheus
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles

  volumes:
  - name: web-content
    emptyDir: {}
  - name: nginx-config
    emptyDir: {}
  - name: fluentbit-config
    emptyDir: {}
  - name: prometheus-config
    emptyDir: {}
  - name: shared-logs
    emptyDir: {}
