apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-mysql
  template:
    metadata:
      labels:
        app: mock-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "testdb"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mock-mysql
  ports:
  - port: 3306
    targetPort: 3306
