apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    app: web-with-sidecar
spec:
  containers:
  - name: web-app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: web-content
      mountPath: /usr/share/nginx/html
  - name: log-processor
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
    - -c
    - |
      while true; do
        echo "$(date): Processing logs..." >> /var/log/shared/processor.log
        if [ -f /var/log/nginx/access.log ]; then
          tail -n 5 /var/log/nginx/access.log >> /var/log/shared/processed-access.log
        fi
        sleep 10
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    - name: processed-logs
      mountPath: /var/log/shared
  initContainers:
  - name: content-setup
    image: busybox:1.35
    command: ["/bin/sh", "-c"]
    args:
    - echo '<h1>Sidecar Demo</h1>' > /web-content/index.html
    volumeMounts:
    - name: web-content
      mountPath: /web-content
  volumes:
  - name: shared-logs
    emptyDir: {}
  - name: processed-logs
    emptyDir: {}
  - name: web-content
    emptyDir: {}
